### ISSUE TITLE
🐛 下载失败

### ISSUE THREAD

**Issue by xmhwws** [SigureMo/mooc-dl#21]
## 调用方式
python mooc-dl.py http://www.icourse163.org/learn/kaopei-1461594163?tid=1462381444#/learn/announce

## 环境信息
-  OS： windows10
-  Python： Python 3.8.5

## 问题简述
下载MOOC视频

使用默认账号：
```
Traceback (most recent call last):
  File "mooc-dl.py", line 216, in <module>
    term_id, course_name = get_summary(url)
  File "mooc-dl.py", line 65, in get_summary
    term_id = re.search(r'termId : "(\d+)"', res).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
修改config.json为自己的账号密码（账号密码无误）：
```
密码错误！
Traceback (most recent call last):
  File "mooc-dl.py", line 216, in <module>
    term_id, course_name = get_summary(url)
  File "mooc-dl.py", line 65, in get_summary
    term_id = re.search(r'termId : "(\d+)"', res).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by SigureMo** [comment]
kaoyan 域下的？不支持

**Comment by xmhwws** [comment]
请问，什么时候支持？

**Comment by SigureMo** [comment]
不会支持

**Comment by xmhwws** [comment]
了解了，打扰您了，抱歉
