### ISSUE TITLE
🐛 下载课程出现错误代码

### ISSUE THREAD

**Issue by LagrangeWang** [SigureMo/mooc-dl#23]
## 环境信息

-  OS： Windows 10 1909 64Bit
-  Python： Python 3.9.1
-  Others： 其它信息

**Comment by LagrangeWang** [comment]
Traceback (most recent call last):
  File "I:\mooc-dl\mooc-dl.py", line 28, in <module>
    CONFIG = Config()
  File "I:\mooc-dl\utils\config.py", line 7, in __init__
    self._jObject = json.load(f)
  File "D:\Program Files\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\Program Files\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 5 column 14 (char 70)

上述为错误信息，不知为啥放在模板里显示不了，我就重新发了一遍。

**Comment by SigureMo** [comment]
修改 config.json 了？应该是里面出现了非法字符……

**Comment by LagrangeWang** [comment]
修改了保存路径，如下所示
{
  "username": "",
  "password": "",
  "resolution": 0,
  "root": "I:\Download\MOOC",
  "num_thread": 30,
  "overwrite": false,
  "file_path_template": "{base_dir}{sep}{cnt_1} {chapter_name}{sep}{cnt_2} {lesson_name}{sep}{cnt_3} {unit_name}",
  "file_types": [1, 3, 4],
  "use_ffmpeg": false
}

**Comment by SigureMo** [comment]
```
"root": "I:/Download/MOOC",
```
这样试试

**Comment by LagrangeWang** [comment]
> ```
> "root": "I:/Download/MOOC",
> ```
> 
> 这样试试

大佬你也太机智了，我刚想说这样试下，次级路径换成“/”，至少保证本页的例子下载正常，很给力0.0

最后提示：
merging 7/8
Done!
这样子是正常的吗

**Comment by SigureMo** [comment]
问题解决了就好
