### ISSUE TITLE
🐛 解析 `parse_resource` 未完成，然后报错，无法下载

### ISSUE THREAD

**Issue by b4imetu** [SigureMo/mooc-dl#24]
## 调用方式

登录成功：

```
PS D:\Downloads\mooc-dl-master> python mooc-dl.py https://www.icourse163.org/course/BUPT-1002543002?tid=1461142443
通信原理 - 北京邮电大学
1002543002
parse_resource 216/313
```

## 环境信息

-  OS： 20H2 19042.789
-  Python： Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
-  Others： 其它信息

## 问题简述

```
Traceback (most recent call last):
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Downloads\mooc-dl-master\mooc-dl.py", line 233, in <module>
    url, file_path, params = parse_resource(resource, token)
  File "D:\Downloads\mooc-dl-master\mooc-dl.py", line 92, in parse_resource
    res = spider.post("https://vod.study.163.com/mob/api/v1/vod/videoByNative", data=data)
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

## 预期行为

解析 `parse_resource` 未完成，然后报错，目前使用公共WiFi，如果是网络问题，我晚上在家里再试一遍

## 额外信息

`config.json`

```
{
  "username": "xxxxxxxx",
  "password": "xxxxxxx",
  "resolution": 0,
  "root": "D:/Download/MOOC",
  "num_thread": 30,
  "overwrite": false,
  "file_path_template": "{base_dir}{sep}{cnt_1} {chapter_name}{sep}{cnt_2} {lesson_name}{sep}{cnt_3} {unit_name}",
  "file_types": [1, 3, 4],
  "use_ffmpeg": true
}
```

**Comment by SigureMo** [comment]
> 如果是网络问题，我晚上在家里再试一遍

便如你猜想一般……

**Comment by b4imetu** [comment]
谢谢，确实是网络问题，已经解决了（能麻烦删一下issue吗，谢谢啦

**Comment by b4imetu** [comment]
谢谢，确实是网络问题，已经解决了（能麻烦删一下issue吗，谢谢啦 @SigureMo
