### ISSUE TITLE
🐛 下载时出现「FileNotFoundError」

### ISSUE THREAD

**Issue by cainiao1992** [SigureMo/mooc-dl#39]
## 调用方式

```
python mooc-dl.py https://www.icourse163.org/course/SWJTU-1207477804
```

## 环境信息

-  OS： Windows 11
-  Python： 3.8.10

## 问题简述

```
心理咨询理论和技术 - 西南交通大学
1207477804
Traceback (most recent call last):
  File "D:\XMIND\MoocDownload\mooc-dl\utils\crawler.py", line 26, in download_bin
    with open(tmp_path, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '心理咨询理论和技术 - 西南交通大学\\11 团体心理工作技术\\11.1 团体咨询技术：保护干预 11.2 团体咨询技术：激励干预 11.2.1 激励干预1 11.2.2 激励干预2 11.3 团体过程分析 11.3.1 团体过程分析概述 11.3.2 团体过程分析模型 11.4 组员的行为 11.4.1 识别难处理的组员 11.4.2 特罗泽的分类：阻抗行为、操控行为、帮助行为 11.4.3 特罗泽的分类：情绪性行为、小团体行为\\11.1.1 团体咨询技术：保护干预_zh.srt.t'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mooc-dl.py", line 311, in <module>
    url, file_path, params = parse_resource(resource, token)
  File "mooc-dl.py", line 184, in parse_resource
    spider.download_bin(srt_url, srt_path)
  File "D:\XMIND\MoocDownload\mooc-dl\utils\crawler.py", line 35, in download_bin
    os.remove(tmp_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '心理咨询理论和技术 - 西南交通大学\\11 团体心理工作技术\\11.1 团体咨询技术：保护干预 11.2 团体咨询技术：激励干预 11.2.1 激励干预1 11.2.2 激励干预2 11.3 团体过程分析 11.3.1 团体过程分析概述 11.3.2 团体过程分析模型 11.4 组员的行为 11.4.1 识别难处理的组员 11.4.2 特罗泽的分类：阻抗行为、
操控行为、帮助行为 11.4.3 特罗泽的分类：情绪性行为、小团体行为\\11.1.1 团体咨询技术：保护干预_zh.srt.t'
```

**Comment by SigureMo** [comment]
唔很抱歉我这不能复现这个问题，看起来是移除/写入临时文件时发现已经被移除了，按理说没有手动修改这个文件的话应该是不会有这个问题的，不过就算崩溃应该也没啥问题啊，如果我没记错这是有断点续传机制的，重新运行一下就好了

**Comment by cainiao1992** [comment]
> 该课程已经更新学期了，看看这个学期：https://www.icourse163.org/course/SWJTU-1207477804?tid=1468214507

###

**Comment by SigureMo** [comment]
> 该课程已经更新学期了，看看这个学期：[icourse163.org/course/SWJTU-1207477804?tid=1468214507](https://www.icourse163.org/course/SWJTU-1207477804?tid=1468214507)

我这里试的就是这个学期

**Comment by cainiao1992** [comment]
> > 该课程已经更新学期了，看看这个学期：[icourse163.org/course/SWJTU-1207477804?tid=1468214507](https://www.icourse163.org/course/SWJTU-1207477804?tid=1468214507)
> 
> 我这里试的就是这个学期

后面我用macOS系统就没有这个问题了，谢谢。
